### ISSUE TITLE
Totem Bar

### ISSUE THREAD

**Issue by DDCorkum** [DDCorkum/CTMod#124]
Ref: https://www.curseforge.com/wow/addons/ctmod?comment=1197

**Comment by DDCorkum** [comment]
When you have the options open, I presume you are seeing the draggable region where there ought to be a bar?  i.e., the bar itself is missing but not CT's invisible placeholder.

I will look more into this today.

**Comment by robertzak** [comment]
Yup, that's exactly what I'm seeing. I can see/drag the section for the totem bar when the menu's open, but the bar itself isn't there. I tried to include a screenshot, but I kept getting errors about attaching it.

**Comment by robertzak** [comment]
actually it looks like the bar is showing up somewhat when I logged today however:

1) The call slot is still in it's original location (IE to select call of the elements, ancestor, or spirits)
2) The totemic recall button is over somewhere different. 

So the bar you're rendering seems to only include the 4 totem selections themselves (earth, fire, water, air)

I have a screen shot, but I still can't seem to attach it to this issue. If it would be helpful, I can try to find somewhere else to post the screen shot and link to it instead.

**Comment by robertzak** [comment]
[screenshot](https://drive.google.com/file/d/1j863chSCLrA1ESUzeyoJMw9RjfOow95f/view?usp=sharing)

**Comment by DDCorkum** [comment]
Thank you for this info.  I am now uploading 9.2.0.1e to GitHub and CurseForge which address the screenshot.

I would be really curious if things work well **during and outside combat**.  This includes doing silly things in combat that you wouldn't normally do, such as summoning friends, changing totems, moving them around in your bags, changing targets, or whatever it is that shamans can do while these things are out.

**Comment by robertzak** [comment]
OK. I'm hoping to play after work (~7 hours from now). I will pull down the latest code and try to test some of the in-combat stuff and report back.

I haven't played a shaman before classic, so this bar is new to me, but the key to it seems to be you pick your _Call of.._ spell and then you assign each of the 4 types of totems to that spell and now you can place all 4 at once. There are 3 different call spells so each has a unique set you can configure. Without the bar, it's impossible to configure each spell. So initially I just moved my bars around so I could see/manipulate each loadout.

Anyways, I'll try to mess with updating my totem selections while in combat, and moving the physical totems in my bags around as well, however I think those are just a component required to cast the spell. And I'll keep an eye out for any issues I run into during just general questing.

Thanks again for updating this mod. I've used it as my bar mod since vanilla and I'm not sure what I'd use if it was broken. One of these days I should learn LUA better. I can read most of the code, but not write it beyond some basic tweaks here and there. The upkeep on some of this stuff can be a lot and it'd be good if I could contribute back more than just testing.

**Comment by robertzak** [comment]
Unfortunately the bar seems buggy still. It didn't show up when I logged in. I was going to post that it was invisible..but when I wasn't paying attention it seemed to show up. Unfortunately I didn't notice how/when it finally showed up.

On the plus side, the `Call of the..` is now there and seems functional. I can switch spells and update the totem load out associated with each.

On the downside, the `Totemic Recall` button is still wrong. This time, instead of it being down near my keyring it's missing completely and in it's place I have a button with `Call of the Elements`

I tried changing the `Call of the..` spell to another to see if that new button updated but it seems to have remained `Call of the Elements`.

Here is a [screenshot](https://drive.google.com/file/d/1UEf9VIzlFMRRM1xoE6vST9W1FCCg1L4z/view?usp=sharing)

**Comment by robertzak** [comment]
I think I found the bug, but I haven't had a chance to try out the fix:

I think this line: https://github.com/DDCorkum/CTMod/blob/9.1.5.2/CT_BottomBar/CT_BottomBar_MultiCast.lua#L96

```lua
local oldMultiCastRecallSpellButton_Update = MultiCastSummonSpellButton_Update
```

needs to be changed to:

```lua
local oldMultiCastRecallSpellButton_Update = MultiCastRecallSpellButton_Update

**Comment by robertzak** [comment]
Yup, that 1 line of code appears to have fixed the issues with Totemic Recall. I can submit a MR if you want, but I imagine it's probably just easier for you to make the change when you get a chance.

Also for what it's worth the bar was there/visible when I logged in this time. So I'm not sure if the reason it was briefly hidden had to do with the movement and/or the bad variable assignment.

I'd say once that fix is in, this issue is probably resolved, but I'll try to keep an eye out for any other problems as I'm playing this week if you want.
