### ISSUE TITLE
Update for Cata Classic <3

### ISSUE THREAD

**Issue by gl00wn** [DDCorkum/CTMod#187]
Will there be one? On Beta sadly much Errors and Bars dont show up.
Much Love!

**Comment by robertzak** [comment]
bumping this. I'm happy to help test/debug issues, but I don't know enough about the wow api/lua to fix all the problems in cata and I really don't want to have to stop using ctmod after 20 years. any plans to look at this?

**Comment by robertzak** [comment]
I think I have a fix for CTBottom_bar. However there are a few other lua errors I need to try to figure out (which is total guesswork on my part).

The shaman totem bar is once again being problematic. It's in the default spot instead of where I had it moved to before. Not sure if this is a separate issue or related to one of the lua errors I haven't been able to figure out yet.

In the meantime I started a branch here: https://github.com/robertzak/CTMod/tree/4.4.0_fix_attempt

I have no idea how to actually release these changes though, but I'd like to at least share what I've done (which could be totally wrong) with other people who are still using this mod

**Comment by robertzak** [comment]
I have a fix for the totem bar, and I think all the remaining lua errors. That doesn't mean there aren't other problems though. So far I haven't noticed anything though.

I also bumped the version and added toc files for Cata. Not sure if the wrath ones need to be deleted but it doesn't seem to care and wow no longer shows it as out of date.

I can submit a PR if @DDCorkum responds and wants to review/release what I did so people can get it via the various add-on sites.

In the meantime I did a tag and release from my own repo: https://github.com/robertzak/CTMod/archive/refs/tags/4.4.0_cata_classic_fix.zip

**Comment by DDCorkum** [comment]
@robertzak 
I received your ping.  Definitely interested in promulgating your updates, thank you.

**Comment by robertzak** [comment]
OK. I'll make a PR after work. I want to pull out my version changes and just submit the code changes. That way you can version it however you prefer

**Comment by robertzak** [comment]
well actually I think you're going to need the TOC files I made..so I'll defer to you on how you want to handle that and just submit back what I have done
