### ISSUE TITLE
ct_core opens warband bank tab as a bag

### ISSUE THREAD

**Issue by DaGrump2394** [DDCorkum/CTMod#192]
When you have "...and open all bank slots" under "Player Bank" checked in CT_Core, it opens a 98-slot bag called "Bank Tab Bag (DNT)" for the Warband Tab.  This bag does not automatically close with "...and close when finished".

**Comment by zealvurte** [comment]
The problem is here: https://github.com/DDCorkum/CTMod/blob/0c0fda85bf3dfb09ac5ee02f5a390ca25efec798/CT_Core/CT_Core_Other.lua#L1885 
This isn't using the most appropriate global constants, and it's miscalculating them, resulting in the wrong `bagID`s for opening the bank bags (e.g. for live it results in 5-13 instead of 6-12, which opens the reagent bag, and closes 1 bank bag to open the first warbank bag). It should instead be something like this:
```lua
for i = BACKPACK_CONTAINER+ITEM_INVENTORY_BANK_BAG_OFFSET+1, BACKPACK_CONTAINER+ITEM_INVENTORY_BANK_BAG_OFFSET+NUM_BANKBAGSLOTS, 1 do
```
Though I'd recommend setting a local constant for those rather than calculate them on every event.
