### ISSUE TITLE
Error messages for CTMOD

### ISSUE THREAD

**Issue by Chris-NorthCarolina** [DDCorkum/CTMod#194]
I received 39 error messages. Here are screen shots of a few. 

[CTMod error messages.pptx](https://github.com/user-attachments/files/16619907/CTMod.error.messages.pptx)

**Comment by DDCorkum** [comment]
Thank you for the report.  The root cause was that Blizzard changed the name of a function which had been around since Vanilla, and every single component of CTMod depended on this function near the top of the program.  They also changed a few other functions that were similarly long-lasting, leading to other issues.

Things should be better in 11.0.2.3 which I am now distributing.
