### ISSUE TITLE
CT_ViewPort Options Reset

### ISSUE THREAD

**Issue by Calesta** [DDCorkum/CTMod#90]
Something in the latest update has caused the CT_ViewPort Options to reset.  I see the behavior on multiple characters.  When I login, the settings have been reset.  Sometimes when I logout and login to the same character in the same session (without leaving the application), they seem to 'stick' but not always.

It doesn't take long to setup when they reset but it's certainly a pain.  Hoping you can find the cause quickly so I don't have to revert back to a prior version.  Thanks!

**Comment by DDCorkum** [comment]
The variables are now saved differently than before... I wrote a script to import from old to new (which should run automatically when you open it up) but maybe I am missing something.

Are settings 'sticking' once you have it configured on a character, the way you want it, after the update?    If so, then you can go to "settings import" in the bottom left of the CTMod options window.   Set it up on one character, and then import/export to all characters (assuming you want it the same on them all).

**Comment by Calesta** [comment]
With the update, my settings are not 'sticking'.  I reverted back to the prior version until this can be fixed as I don't want to have to setup the view port every time I login on a different character.  Hopefully, it will be fixed in a later update.

**Comment by DDCorkum** [comment]
Today I went onto a fresh install of classic, with the previous version of CT_Viewport.   I logged onto a toon and set the viewport size to random numbers.

Then I installed the newest version, logged back on, and the viewport size appeared to be unchanged.  I did this on a few characters as a test.

Could you do me a favour and copy/paste whatever text you find in the following file?  I will use it to try recreating your exact setup and see if I can figure out what's wrong.

**.../World of Warcraft/__[edition]__/WTF/Account/[your account name]/[server]/[character]/SavedVariables/CT_Viewport.lua**

This is just a text file with saved viewport settings.  I'll copy/paste it to one of my characters, and then see what happens when I install the latest version -- with luck, I'll encounter the error and then I can diagnose & fix it.

**Comment by Calesta** [comment]
I play retail, not classic, if that makes a difference here.  

Attached is the file you requested.
[CT_Viewport.zip](https://github.com/DDCorkum/CTMod/files/6091565/CT_Viewport.zip)

**Comment by DDCorkum** [comment]
Thanks, I will investigate.   And noted: I'll run the experiment on retail as well

**Comment by DDCorkum** [comment]
I think I found the problem.  Here is a copy of my current development version:

[CTMod 9.0.2.5b SL.zip](https://github.com/DDCorkum/CTMod/files/6096288/CTMod.9.0.2.5b.SL.zip)

**Comment by DDCorkum** [comment]
The flaw was that logging onto each alt for the first time (since 9.0.2.4) causes an overwrite of the saved variables.

9.0.2.4 had logic to detect it was the first time on an older alt, but the script only converted variables to the new format for that toon.   Other toons were deleted by the game client because no explicit instruction was made to preserve them.

The solution in 9.0.2.5b is to make a backup copy of the saved variables, and explicitly preserve this backup when switching alts.   When logging onto an alt for the first time since 9.0.2.4, the script now also recalls this backup and restores settings.


This cannot restore settings that were already lost in 9.0.2.4, but it will prevent the new loss of any toon provided you have logged onto it at least once from 9.0.2.5b onwards.
